### PR TITLE
Add NIP-11 icon URL

### LINKED ISSUE #102: Add support for icon URL in NIP-11 document
Hi!

I'd love to see support for setting a url for a relay icon in the NIP-11 document, just like it's [documented here](https://github.com/nostr-protocol/nips/blob/master/11.md#icon). I'd love to contribute to this myself but I haven't written a single line of C++ code ever before. I'll try to contribute to this but I post this issue in hopes that someone else with actual C++ experience beat me to it.

### PR DESCRIPTION
**Pull request by zappityzap**
Adds the "icon" URL to the NIP-11 document.

Closes #102

### CODE REVIEW

**Comment by 0xtrr** [comment]
Awesome, thank you @zappityzap! I've set up a relay based on the latest commit on this branch and I can confirm that this fix works. If anyone else wants to verify, execute this curl request: `curl -H "Accept: application/nostr+json" https://relay.nostr.lighting`.

**Comment by dskvr** [comment]
@hoytech +1 on that

**Comment by hoytech** [comment]
Sorry for the delay! Thank you!

**Comment by 0xtrr** [comment]
> Sorry for the delay! Thank you!

Thanks for merging Doug, hope you're well!

**Pull request merged**
