### PR TITLE
Add timeout config for router.

### PR DESCRIPTION
**Pull request by braydonf**
A few changes to work with configuration files created by [strfry-tools](https://github.com/braydonf/strfry-tools), this can include hundreds of streams based upon the `kind 3` follows/contacts of an npub and `kind 10002` relay list metadata for each contact.

Related: https://github.com/hoytech/strfry/issues/45#issuecomment-2375257005

### CODE REVIEW

**Comment by braydonf** [comment]
I tested running several concurrent `strfry router` cmds together (180+) and ran into an issue with too many open files. It didn't look like `strfry router` had a threadpool yet, so adding this could also likely help.

**Comment by braydonf** [comment]
I'll leave out the thread pool for this PR. Currently using this branch for my relay.

**Review by hoytech — APPROVED** [review]
I'm very sorry on the delay on merging this! It basically looks good to me. I'm going to merge this and tweak a few minor things, but otherwise looks good. Thanks!

**Comment by hoytech** [comment]
@braydonf - I renamed the param to `connectionTimeout` instead of `timeout` (in case we ever support different types of timeouts). I also refactored slightly and added some docs. Thanks again!

**Comment by braydonf** [comment]
Great, thanks! And also the config reloading, forgot that was something to think about.

**Pull request merged**
