### PR TITLE
Add Alpine Docker

### LINKED ISSUE #63: Dockerfile build fails
I got an error on `docker build . -t myImageName`
I'm on Mac M1 arch, I don't know if it's related

```
 => ERROR [build 7/7] RUN make -j4                                                                                                                                                                                                                20.7s 
------                                                                                                                                                                                                                                                  
 > [build 7/7] RUN make -j4:                                                                                                                                                                                                                            
0.257 perl golpe/gen-fbs.pl                                                                                                                                                                                                                             
0.258 perl golpe/gen-config.pl                                                                                                                                                                                                                          
0.258 golpe/external/rasgueadb/rasgueadb-generate golpe.yaml build                                                                                                                                                                                      
0.261 perl golpe/gen-main.cpp.pl                                                                                                                                                                                                                        
0.284 perl golpe/gen-golpe.h.pl
0.360 perl golpe/external/templar/templar.pl src/tmpls/ strfrytmpl build/StrfryTemplates.h
0.371 cd golpe/external/uWebSockets && make -j libuWS.a
0.381 make[1]: warning: -j0 forced in submake: resetting jobserver mode.
0.382 make[1]: Entering directory '/build/golpe/external/uWebSockets'
0.382 g++ -std=c++17 -O2 -g -Wall -fPIC    -c -o src/Extensions.o src/Extensions.cpp
0.383 g++ -std=c++17 -O2 -g -Wall -fPIC    -c -o src/Group.o src/Group.cpp
0.383 g++ -std=c++20 -O3 -g -Wall -fPIC  -DDOCOPT_HEADER_ONLY -Iinclude -Ibuild -Isrc -Igolpe/external -Igolpe/external/lmdbxx/include -Igolpe/external/config/include -Igolpe/external/json/include -Igolpe/external/PEGTL/include -Igolpe/external/hoytech-cpp -Igolpe/external/docopt.cpp -Igolpe/external/loguru -Igolpe/external/parallel-hashmap -Iexternal/negentropy/cpp -MMD -MP -MT golpe/logging.o -MF golpe/logging.d -c golpe/logging.cpp -o golpe/logging.o
0.385 g++ -std=c++17 -O2 -g -Wall -fPIC    -c -o src/Networking.o src/Networking.cpp
0.386 g++ -std=c++20 -O3 -g -Wall -fPIC  -DDOCOPT_HEADER_ONLY -Iinclude -Ibuild -Isrc -Igolpe/external -Igolpe/external/lmdbxx/include -Igolpe/external/config/include -Igolpe/external/json/include -Igolpe/external/PEGTL/include -Igolpe/external/hoytech-cpp -Igolpe/external/docopt.cpp -Igolpe/external/loguru -Igolpe/external/parallel-hashmap -Iexternal/negentropy/cpp -MMD -MP -MT build/main.o -MF build/main.d -c build/main.cpp -o build/main.o
0.386 g++ -std=c++17 -O2 -g -Wall -fPIC    -c -o src/Hub.o src/Hub.cpp
0.390 g++ -std=c++17 -O2 -g -Wall -fPIC    -c -o src/Node.o src/Node.cpp
0.397 g++ -std=c++17 -O2 -g -Wall -fPIC    -c -o src/WebSocket.o src/WebSocket.cpp
0.412 g++ -std=c++17 -O2 -g -Wall -fPIC    -c -o src/HTTPSocket.o src/HTTPSocket.cpp
0.419 g++ -std=c++17 -O2 -g -Wall -fPIC    -c -o src/Socket.o src/Socket.cpp
0.428 g++ -std=c++17 -O2 -g -Wall -fPIC    -c -o src/Epoll.o src/Epoll.cpp
0.438 g++ -std=c++17 -O2 -g -Wall -fPIC    -c -o src/Room.o src/Room.cpp
0.709 g++ -std=c++20 -O0 -g -Wall -fPIC  -DDOCOPT_HEADER_ONLY -Iinclude -Ibuild -Isrc -Igolpe/external -Igolpe/external/lmdbxx/include -Igolpe/external/config/include -Igolpe/external/json/include -Igolpe/external/PEGTL/include -Igolpe/external/hoytech-cpp -Igolpe/external/docopt.cpp -Igolpe/external/loguru -Igolpe/external/parallel-hashmap -Iexternal/negentropy/cpp -MMD -MP -MT build/config.o -MF build/config.d -c build/config.cpp -o build/config.o
5.414 ar rs libuWS.a src/Extensions.o src/Group.o src/Networking.o src/Hub.o src/Node.o src/WebSocket.o src/HTTPSocket.o src/Socket.o src/Epoll.o src/Room.o
5.422 ar: creating libuWS.a
5.452 make[1]: Leaving directory '/build/golpe/external/uWebSockets'
5.452 g++ -std=c++20 -O3 -g -Wall -fPIC  -DDOCOPT_HEADER_ONLY -Iinclude -Ibuild -Isrc -Igolpe/external -Igolpe/external/lmdbxx/include -Igolpe/external/config/include -Igolpe/external/json/include -Igolpe/external/PEGTL/include -Igolpe/external/hoytech-cpp -Igolpe/external/docopt.cpp -Igolpe/external/loguru -Igolpe/external/parallel-hashmap -Iexternal/negentropy/cpp -MMD -MP -MT src/Decompressor.o -MF src/Decompressor.d -c src/Decompressor.cpp -o src/Decompressor.o
12.21 g++: fatal error: Killed signal terminated program cc1plus
12.21 compilation terminated.
12.21 make: *** [golpe/rules.mk:31: build/config.o] Error 1
12.21 make: *** Waiting for unfinished jobs....
------
Dockerfile:13
--------------------
  11 |     RUN git submodule update --init
  12 |     RUN make setup-golpe
  13 | >>> RUN make -j4
  14 |     
  15 |     FROM ubuntu:jammy as runner
--------------------
ERROR: failed to solve: process "/bin/sh -c make -j4" did not complete successfully: exit code: 2
```

### PR DESCRIPTION
**Pull request by theAkito**
Fix #63.

### CODE REVIEW

**Comment by hoytech** [comment]
Hey sorry for the delay on this. Can you please make it so the default one stays Ubuntu, and check in the `.alpine` one separately? This makes a cleaner diff, and ensures we won't break anyone's workflow. It's possible some people are using the default and would be surprised if it changed. Thank you!

**Comment by theAkito** [comment]
> Hey sorry for the delay on this. Can you please make it so the default one stays Ubuntu, and check in the `.alpine` one separately? This makes a cleaner diff, and ensures we won't break anyone's workflow. It's possible some people are using the default and would be surprised if it changed. Thank you!

As a temporary solution, it might be acceptable, but it's definitely not a long-term solution, because the Alpine image should be the default, as it is better in every way & everyone should use it by default.

I actually wanted to entirely delete the Ubuntu one, however I just kept it as a backup, in case someone needs some customisation or wants to add a custom product to a downstream image, which might only work on Ubuntu.
Otherwise, the Ubuntu one is utterly useless & should not be used, at all, anymore.

So, as a temporary solution, the rename would be fine, but it would need to have a time-bomb attached to it, which will change the defaults at some point. Obviously, in the meantime, all users would need to be informed ahead about the change, so they can prepare.

The other thing is, that the `docker-compose.yml` is supposed to be overhauled either way, since we need Docker Hub or GitHub Container Registry builds, anyway. Then, we can deal with this through tags, etc.

No matter the choice & decision, it must be made sure, that the Alpine image will end up as the default in the end, because there is literally no reason to use the Ubuntu one anymore, except for edge cases, like custom downstream images with custom software, which only runs on Ubuntu for whatever reason.

**Comment by hoytech** [comment]
Alpine uses musl instead of glibc right? I've experienced severe performance regressions with musl in the past so I personally steer clear of it for production servers.

**Comment by theAkito** [comment]
> Alpine uses musl instead of glibc right? I've experienced severe performance regressions with musl in the past so I personally steer clear of it for production servers.

Do you have any data on that, counting in all performance factors, like overall bloat, etc.?

The first thing I thought, when reading that, it seemed to me that, even if there were severe performance regressions with musl, the overall system of the entire image is so much slimmer & quicker, it should still be overall more performant, than an Ubuntu one.

Either way, if you want to keep Ubuntu the default for some reason, it's your repository, so it'll happen, but I definitely see no technical & inherent reason in this situation to not have the Alpine one as the default image.

**Comment by hoytech** [comment]
You're right, I don't have any specific reasons to think there would be a regression for this project. I'll merge it, and we'll see if anybody complains. Thank you!

**Comment by theAkito** [comment]
@hoytech

Nice, let's give Alpine a chance. 🙂

If anyone complains, give me a ping & I'll look into it. 😀

**Comment by theAkito** [comment]
> It seems @theAkito assumes that when the image is slimmer that it automaticly means it will have higher performance

No, less things mean less to ignore & less to break. Disk space is not a big issue, nowadays.

> as far as I know the redundant/unused libraries in the Ubuntu image will just take up some unnecessary diskspace, but don't affect performance in any way.

As far as you know. As far as I know, any unnecessary stuff is generally a potential performance hindrance.

> And the one area where musl is considerably slower is in memory allocations, which happens a lot in strfry because of the lmdb database. So I would not be surprised if the Alpine image would be less performant after all.

Well, before someone calls me an Alpine freak or anything, I will make one thing clear.

If anyone can provide actually valid data, that the newest Alpine versions (NOT the ones from 2 years ago, when there were performance issues, which are already fixed) are somehow *less* performant, I will be the first to jump up & change the default image.

The reason, I think Alpine is usually the right choice, is because it works just as well as bigger images, with performance benefits in the broad view.

I also have lots of experience with running Alpine in production & there is rarely an Alpine specific issues. 99% of issues are app or library related issues, which are neither related to musl nor Alpine.

> Im not sure if that is worth the obscure bugs and incompatibilities that might be introduced by switching to Alpine.

This is the expression I agree the least with, because it's basically saying "I've used Ubuntu for so many years & Alpine is new, so Alpine must be scary."

Please, check out the Alpine Dockerfile yourself. It's the same crap, that is in the Ubuntu image. If there is truly some error somewhere, it's not related to Alpine, but to the libraries or apps.

For example, most of this project is handled in C++, which is a very low level language, where you have to be extremely particular, specific & careful about compilation flags, etc. especially when optimising everything.

That said, the data about this subject is what matters. I'm running this Alpine relay since I created the Dockerfile, i.e. before this image was merged & it works fine. So, from our anecdotal experiences, it's one experience versus another, i.e. there is no consensus on it being broken, especially when you are to this point the only one experiencing an issue.

You should probably open an issue about your specific problem, which is specific to your setup & then we can check out what the actual issue in your scenario is. Maybe we just need another compilation flag or whatever. 🙂

**Comment by theAkito** [comment]
> As far as I recall the reason why malloc() is slower on Alpine was not because of a performance issue, but because of extra security checks that musl does.

If that is the case, isn't that what we want, especially when we are dealing with encrypted stuff in this app?

> I never seen any of those images crash untill the move to Alpine. That you don't experience the issue could be related to a lot of things (x86 vs ARM, the amount of traffic your instance gets, etc.).
> 
> Im just reporting the issue, and it isnt my intention to start a discussion whether Alpine is better than Debian/Ubuntu. As long as the image runs stable I don't really care about that.

That's totally fair & I get that. 😀

I think, I would just rather find out the actual issue behind this insufficient experience, rather than just ditching Alpine & basically putting it in a coffin, because once we switch, without finding out the underlying issue, on the grounds that "Alpine just did not work", then nobody will ever even try it & that would be rather disappointing. 😕

**Comment by theAkito** [comment]
> I do like the minimal concept of Alpine, but unfortunately I mostly test strfry on Debian/Ubuntu so it may make sense for this to be the default. Or should we name them `Dockerfile.ubuntu` and `Dockerfile.alpine` to avoid blessing one as the official one?

That's fair. 👍🏻


Even though, I have seen this type of naming, I find it more intuitive to do it the other way around, because file extensions dictate what is shown in the IDE in what way.

Id est:
```
ubuntu.Dockerfile
alpine.Dockerfile
```

Not sure, if it matters that much, though.

That said, I think it makes definitely sense to explain the situation transparently to potential users.

I can open a Pull Request with the updated file names & an explanation in the README. Actually, I don't even see a Docker section there, at all, so I guess I could add it altogether & in addition to that explain the difference & basically say, that Alpine is the slim one, but if it does not work, Ubuntu is more tested & has proven to be more reliable for this specific project.

I planned to also rework the `docker-compose.yaml` file, so might as well create two, each with their own build target & potential fixes, if we ever need different settings for different images. 🙂

**Comment by hoytech** [comment]
Ahh yeah that makes sense about the file extension naming. More docs are always welcome, thanks! You may want to add it to this file:

https://github.com/hoytech/strfry/blob/master/docs/DEPLOYMENT.md

Or maybe create a new DOCKER.md file. Thank you!

**Comment by theAkito** [comment]
> 

@kroese

Greetings 👋🏻

Thank you very much for your help! That clears things up a lot. 🙂

@hoytech

I still want to add documentation regarding the Docker setup, but I guess Alpine can stay the default for now, since this error is absolutey confirmed to be not related to Alpine? 🙂

**Pull request merged**
