### PR TITLE
Add a sample docker-compose file

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Added a simple docker-compose.yaml file for spinning up the relay with docker easily.

### CODE REVIEW

**Comment by hoytech** [comment]
Thanks!

**Comment by ralyodio** [comment]
this isn't working when i proxy with nginx?

**Comment by niteshbalusu11** [comment]
> this isn't working when i proxy with nginx?

I use Caddy inside the same docker compose file and it works fine for me.

**Comment by ralyodio** [comment]
what's Caddy?

**Comment by niteshbalusu11** [comment]
https://caddyserver.com/docs/

It's like nginx to reverse proxy. I'm sure nginx will work as well.

**Pull request merged**
